name: Deploy VitePress to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run docs:build

      - name: Verify build output
        run: |
          ls -la .vitepress/dist
          [ -f .vitepress/dist/index.html ] || exit 1

      - name: Add CNAME
        run: |
          mkdir -p .vitepress/dist
          echo "jszhan.top" > .vitepress/dist/CNAME
          echo "www.jszhan.top" >> .vitepress/dist/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .vitepress/dist
          retention-days: 1  # 添加保留时间

      - name: Deploy
        uses: actions/deploy-pages@v3
        timeout-minutes: 5  # 添加超时设置