name: Deploy VitePress

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        if: "!env.ACT"
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm run docs:build

      - name: Verify build output
        run: |
          ls -la .vitepress/dist
          [ -f .vitepress/dist/index.html ] || exit 1

      - name: Upload artifact (Temp)
        uses: actions/upload-artifact@v4
        with:
          name: vite-dist
          path: .vitepress/dist
          retention-days: 1

      - name: Upload for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .vitepress/dist

      - name: Deploy
        uses: actions/deploy-pages@v4
        timeout-minutes: 5