name: Deploy VitePress

on:
  push:
    branches: [master]

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install
          pnpm list --depth 0

      - name: Build
        run: pnpm run docs:build

      - name: Validate build
        run: |
          ls -la .vitepress/dist
          [ -f .vitepress/dist/index.html ] || { echo "Build failed - no index.html"; exit 1; }

      - name: Prepare CNAME
        run: |
          mkdir -p .vitepress/dist
          echo "jszhan.top" > .vitepress/dist/CNAME
          echo "www.jszhan.top" >> .vitepress/dist/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: vite-press
          path: .vitepress/dist
          retention-days: 2

      - name: Deploy
        uses: actions/deploy-pages@v3
        timeout-minutes: 10